- hosts: all
  become: true
  tasks:
    - import_tasks: ../tasks/install-apt-https.yml
    - import_tasks: ../tasks/install-containerd.yml
    - import_tasks: ../tasks/disable-swap.yml
    - import_tasks: ../tasks/install-kubernetes.yml
    
    - name: Generate certificate key
      command: kubeadm certs certificate-key
      register: certificate_key

    - import_tasks: ../tasks/configure-kubelet.yml
      vars:
        node_ip: "{{ node_ip }}"
    
    - import_tasks: ../tasks/init-kubernetes-cluster.yml
      vars:
        node_ip: "{{ node_ip }}"
        node_name: "{{ node_name }}"
        pod_network_cidr: "{{ pod_network_cidr }}"
        cert_key: "{{ certificate_key.stdout_lines[0] }}"

    - name: Generate join control-plane command
      command: kubeadm token create --print-join-command --certificate-key={{ certificate_key.stdout_lines[0] }}
      register: join_control_plane

    - name: Generate join worker command
      command: kubeadm token create --print-join-command
      register: join_worker

    - debug:
        var: join_control_plane.stdout_lines

    - debug:
        var: join_worker.stdout_lines

    - name: Prepare join-as-worker.sh
      become: false
      delegate_to: localhost
      copy:
        content: "{{ join_worker.stdout_lines[0] }}"
        dest: ./join-as-worker.sh

    - name: Prepare join-as-control-plane.sh
      become: false
      delegate_to: localhost
      copy:
        content: "{{ join_control_plane.stdout_lines[0] }} --apiserver-advertise-address=$NODE_IP --v=5"
        dest: ./join-as-control-plane.sh
