- name: Add br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Configure ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure br_netfilter
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes